### ISSUE TITLE
Collaborate with PropertyWebBuilder

### ISSUE THREAD

**Issue by etewiah** [Dino-SaaS/Argon#2]
Hey, I love what you're doing with dinosaas - thanks for creating it!!

I'm reaching out because I'd love to collaborate with you to build a property listings website on top of argon.  Its a great use-case which could really show the usefulness of Argon.

I already built an open source rails engine so it would just be a question of adapting it to fit with Argon:

https://github.com/etewiah/property_web_builder

Is this something you'd be interested in exploring?

**Comment by TimKJones** [comment]
Thanks for reaching out! property_web_builder seems like an impressive project! I actually co-founded a real estate tech company called Cribspot awhile back. We built a few different versions of the site with property search functionality.

I'm currently spending all my productive time on a new project, and won't have any spare cycles to lend to adapting Argon to your project. I think it's a great idea though! Let me know if you think I can help in a small way and I'll let you know if I have time.

**Comment by etewiah** [comment]
Thanks for the reply.  I've dug a little bit into cribspot - you guys got quite far with it!  Shame it didn't work out, it could have been quite big.

I can understand you not having the time to work on this.  I'll dig a bit more to see what it will take to incorporate pwb into Argon. I'm also going to reach out to connect on linkedin if that's okay with you.   If any of my proptech projects take off it could be interesting to have a chat with you about perhaps collaborating.
